
name: CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  # This workflow contains a single job called "build"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Setup MSBuild  
        uses: microsoft/setup-msbuild@v1.1
      
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.6
        
      - name: Restore Nuget Packages
        run: nuget restore NapierBankingService.sln
        
      - name: Build the Soloution
        run: msbuild NapierBankingService.sln
        
      - name: Test
        run: dotnet test --no-restore --verbosity normal

      
